### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by vitaly-kamluk** [msuhanov/Linux-write-blocker#5]
Hello Maxim,
This is great project and very useful, however we ran into license compatibility issues which prevent your code to be used widely. For example, our project uses GPLv3 which is not backwards compatible with GPLv2, that you are using, unless you explicitly allow this. 
This part is critical and shall be included into current license:
"  This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
(at your option) any later version."

This came from the recommendation included in the end of your own GPLv2 license file (see your LICENSE file after line 282)? The best way I think is to add another file (i.e. DISTRIBUTION) and include a reference to it inside a comment line in the patch files that you created. Is it something you could do for the benefit of opensource community?

Looking forward to your help!

Regards,
Vitaly

**Comment by msuhanov** [comment]
Hello.

1. The Linux kernel is distributed under the terms of the GNU GPLv2 (although some parts of the kernel allow "any later version" to be used, the _block/blk-core.c_ file is covered by the GNU GPLv2 only), so I can't use the GNU GPLv2+/GPLv3/GPLv3+ for the patch. If I apply a different license to the patch (treated as a separate work), this will cause legal problems when distributing the patched kernel.

I can apply a different license to the userspace tools and to the udev rule, but I also want to allow the tivoization for these tools and for this rule, as well as for their derivatives (to attract vendors of hardware write blockers and forensic duplicators). So, I will keep the GNU GPLv2 as the current license.

2. Attaching a license file to a program is enough to enable licensing under the terms and conditions included in this license file (and enough to state the version of the license to be used). The "How to Apply These Terms to Your New Programs" section of the GNU GPLv2 contains an advice (and an obvious overkill), not an obligation, because it's not a part of the terms and conditions.

**Comment by vitaly-kamluk** [comment]
Hi Maxim,
It seems more complicated than I initially thought, but we'd love to use and promote your research. Could you please contact us by email at bitscout[at]kaspersky[.]com? We would like to find a solution to enable others leverage your work.

Kind regards,
Vitaly

**Comment by msuhanov** [comment]
I authorize the use of Linux write blocker in Bitscout (this statement is made explicitly as requested in the e-mail conversation).

**Comment by vitaly-kamluk** [comment]
Thank you, Maxim!
